# Generated by Django 5.2.1 on 2025-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
