<template>
  <div class="p-6 max-w-sm mx-auto space-y-6">
    <h2 class="text-xl font-bold text-center">ورود / ثبت‌نام با شماره موبایل</h2>

    <p class="text-sm text-center text-gray-600">
      اگر حساب دارید وارد می‌شوید، در غیر این صورت برای شما حساب ساخته می‌شود.
    </p>

    <!-- مرحله اول: شماره تلفن -->
    <form @submit.prevent="handleSendOtp" v-if="step === 1" class="space-y-4">
      <input v-model="phone" type="text" placeholder="شماره تلفن" class="w-full p-2 border rounded" />
      <button class="bg-blue-600 text-white w-full p-2 rounded" type="submit">
        دریافت کد تأیید
      </button>
    </form>

    <!-- مرحله دوم: کد تأیید + نقش (فقط اگر کاربر جدید باشد) -->
    <form @submit.prevent="handleVerifyOtp" v-if="step === 2" class="space-y-4">
      <input v-model="otp" type="text" placeholder="کد تأیید" class="w-full p-2 border rounded" />

      <select v-if="isNewUser" v-model="role" class="w-full p-2 border rounded">
        <option disabled value="">انتخاب نقش</option>
        <option value="customer">مشتری</option>
        <option value="provider">متخصص</option>
      </select>

      <button class="bg-green-600 text-white w-full p-2 rounded" type="submit">
        {{ isNewUser ? 'ثبت‌نام و ورود' : 'ورود' }}
      </button>
    </form>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import axios from 'axios'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'

const router = useRouter()
const user = useUserStore()

const step = ref(1)
const phone = ref('')
const otp = ref('')
const role = ref('')
const isNewUser = ref(false)

const handleSendOtp = async () => {
  if (!phone.value) {
    alert('شماره تلفن را وارد کنید')
    return
  }

  try {
    // ارسال OTP (ماک) + بررسی وجود کاربر
    alert(`کد تأیید به ${phone.value} ارسال شد (ماک: 123456)`)

    // بررسی وجود کاربر از API (واقعی)
    const res = await axios.post('/api/auth/login/', {
      phone: phone.value,
      password: 'fakepass' // رمز جعلی برای بررسی وجود
    })

    isNewUser.value = false
    step.value = 2
  } catch (err) {
    if (err.response?.status === 400) {
      // کاربر وجود ندارد → ثبت‌نام لازم است
      isNewUser.value = true
      step.value = 2
    } else {
      alert('خطا در بررسی شماره')
    }
  }
}

const handleVerifyOtp = async () => {
  if (!otp.value || (isNewUser.value && !role.value)) {
    alert('لطفاً کد تأیید و نقش را وارد کنید')
    return
  }

  if (otp.value !== '123456') {
    alert('کد تأیید نادرست است')
    return
  }

  try {
    if (isNewUser.value) {
      // ثبت‌نام واقعی
      await axios.post('/api/auth/signup/', {
        phone: phone.value,
        password: 'autogenerated',
        role: role.value
      })
    }

    // ورود واقعی (در هر دو حالت)
    const res = await axios.post('/api/auth/login/', {
      phone: phone.value,
      password: 'autogenerated'
    })

    user.login(res.data.access, res.data.role)
    router.push(res.data.role === 'customer' ? '/dashboard/customer' : '/dashboard/provider')
  } catch (err) {
    alert('خطا در ورود یا ثبت‌نام')
  }
}
</script>
